import Article from "@sections/Article";
import Footer from "@sections/Footer";
import Header from "@sections/Header";
import RelatedArticles from "@sections/RelatedArticles";
import { ArticleModel } from "models/ArticleModel";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "styles/Home.module.css";

const ArticlePage: NextPage<{ article: ArticleModel }> = ({ article }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Runo Headless</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main>
        <Article article={article} />
        <RelatedArticles articles={article.relatedArticles} />
      </main>
      <Footer />
    </div>
  );
};

export default ArticlePage;

export async function getStaticPaths() {
  return {
    paths: [{ params: { id: "1" } }, { params: { id: "2" } }],
    fallback: false, // can also be true or 'blocking'
  };
}

// `getStaticPaths` requires using `getStaticProps`
export async function getStaticProps(context: { id: string }) {
  const article: ArticleModel = {
    title: "Title of Article",
    badge: "Fashion",
    description: "Short Description of the article",
    image: "images/Rectangle 9.png",
    createdAt: "08.08.2021",
    readingTime: "3 minutes",
    text: {
      __html:
        "<p>Seamlessly syndicate cutting-edge architectures rather than collaborative collaboration and idea-sharing. Proactively incubate visionary interfaces whereas premium benefits. Seamlessly negotiate ubiquitous leadership skills rather than parallel ideas. Dramatically visualize superior interfaces for best-of-breed alignments. Synergistically formulate performance based users through customized relationships. Interactively deliver cross-platform ROI via granular systems. Intrinsicly enhance effective initiatives vis-a-vis orthogonal outsourcing. Rapidiously monetize market-driven opportunities with multifunctional users. Collaboratively enhance visionary opportunities through revolutionary schemas. Progressively network just in time customer service without real-time scenarios.</p>",
    },
    tags: ["ADVENTURE", "PHOTO", "DESIGN"],
    author: {
      name: "Jennifer Lawrence",
      profession: "Designer",
      image: "images/Nicolas Cage.png",
    },
    relatedArticles: [
      {
        title: "Title of related article 1",
        createdAt: "08.08.08",
        badge: "Fashion",
        description: "Description of the article",
        image: "images/Rectangle 9.png",
      },
      {
        title: "Title of related article 2",
        createdAt: "08.08.08",
        badge: "Fashion",
        description: "Description of the article",
        image: "images/Rectangle 9.png",
      },
      {
        title: "Title of related article 3",
        createdAt: "08.08.08",
        badge: "Fashion",
        description: "Description of the article",
        image: "images/Rectangle 9.png",
      },
    ],
  };
  return {
    // Passed to the page component as props
    props: { article },
  };
}
