import Article from "@sections/Article";
import RelatedArticles from "@sections/RelatedArticles";
import { ArticleModel } from "models/ArticleModel";
import type { NextPage } from "next";
import Head from "next/head";
import { fetchArticle, fetchArticlesPaths } from "service/aem";
import styles from "styles/Home.module.css";

const ArticlePage: NextPage<{ article: ArticleModel }> = ({ article }) => {
  const title = `${article.title.toString()}  - Runo Headless`;
  return (
    <div className={styles.container}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Article article={article} />
      {article.relatedArticles.length > 0 && (
        <RelatedArticles articles={article.relatedArticles} />
      )}
    </div>
  );
};

export default ArticlePage;

export async function getStaticPaths() {
  const paths = await fetchArticlesPaths();
  return {
    paths,
    fallback: false,
  };
}

export async function getStaticProps(context: { params: { id: string } }) {
  const article = await fetchArticle(context.params.id);

  return {
    props: { article },
  };
}
