import Carousel from "@sections/Carousel";
import FeaturedArticle from "@sections/FeaturedArticle";
import PopularTopics from "@sections/PopularTopics";
import RelatedArticles from "@sections/RelatedArticles";
import { ArticleCompactModel } from "models/ArticleModel";
import type { NextPage } from "next";
import Head from "next/head";
import {
  fetchArticleList,
  fetchEditorPicks,
  fetchFeatured,
  fetchRecentArticles,
} from "service/aem";

import styles from "../styles/Home.module.css";

const Home: NextPage<{
  featuredArticle: ArticleCompactModel;
  topArticle: ArticleCompactModel;
  popularArticles: ArticleCompactModel[];
  editorPicks: ArticleCompactModel[];
}> = ({ featuredArticle, topArticle, popularArticles, editorPicks }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home - Runo Headless</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 style={{ visibility: "hidden", height: "0" }}>Runo Home Page</h1>
      <Carousel article={topArticle} />
      <PopularTopics articles={popularArticles} />
      <FeaturedArticle article={featuredArticle} />
      <RelatedArticles
        articles={editorPicks}
        sectionTitle="Editor's Pick"
        largeTitle
      />
    </div>
  );
};

export default Home;

export async function getStaticProps() {
  const featuredArticle = await fetchFeatured();
  // {
  //   title: "Featured Title",
  //   badge: "Adventure",
  //   createdAt: "08.05.2003",
  //   description: "Nice description",
  //   image: "images/Rectangle 9.png",
  //   readingTime: "5",
  //   id: "mockid",
  // };
  const editorPicks = await fetchEditorPicks();

  const topArticle = await fetchRecentArticles();
  // {
  //   title: "Featured Title",
  //   badge: "Adventure",
  //   createdAt: "08.05.2003",
  //   description: "Nice description",
  //   image: "images/Rectangle 9.png",
  //   readingTime: "5",
  //   id: "mockid",
  // };

  // const popularArticles = [
  //   {
  //     badge: "adventure",
  //     createdAt: "08.07.2019",
  //     description: "This is a mock description",
  //     id: "mock-id",
  //     image: "images/Rectangle 9.png",
  //     title: "Mock Title",
  //   },
  //   {
  //     badge: "adventure",
  //     createdAt: "08.07.2019",
  //     description: "This is a mock description",
  //     id: "mock-id2",
  //     image: "images/Rectangle 9.png",
  //     title: "Mock Title 2",
  //   },
  // ];
  const popularArticles = await fetchArticleList();

  return {
    props: { featuredArticle, topArticle, popularArticles, editorPicks },
  };
}
