import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Article from "../sections/Article";
import Header from "../sections/Header";
import RelatedArticles from "../sections/RelatedArticles";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main>
        <Article />
        <RelatedArticles />
      </main>
    </div>
  );
};

export default Home;
