import Article from "@sections/Article";
import Footer from "@sections/Footer";
import Header from "@sections/Header";
import RelatedArticles from "@sections/RelatedArticles";
import type { NextPage } from "next";
import Head from "next/head";

import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main>
        <Article />
        <RelatedArticles />
      </main>
      <Footer />
    </div>
  );
};

export default Home;
